server:
  port: 8085


#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: testdb


# Database connection properties for mySql
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

# db connection for the postgresql
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: root


